#   ____                              _               _
#  |  _ \    ___   _ __   _ __ ___   (_)  ___   ___  (_)   ___    _ __    ___
#  | |_) |  / _ \ | '__| | '_ ` _ \  | | / __| / __| | |  / _ \  | '_ \  / __|
#  |  __/  |  __/ | |    | | | | | | | | \__ \ \__ \ | | | (_) | | | | | \__ \
#  |_|      \___| |_|    |_| |_| |_| |_| |___/ |___/ |_|  \___/  |_| |_| |___/
#


# This plugin heavily relies upon MySQL.
# Without MySQL player groups could not be globally transferred across bungee-servers!

# MySQL Server Host
Host: "localhost"

# MySQL Server Port
Port: "3306"

# MySQL Server Database
Database: "database"

# MySQL Server Username
Username: "username"

# MySQL Server Password
Password: "password"

# This is the default group that will be created when the plugin first starts up.
# Please note that prefix's & suffix's are not set by default!
DefaultGroup: "member"

# This time is measure in SECONDS! This time is how often the plugin will sync groups.
# For example, if a group was deleted on your hub server then the rest of the servers connected to the
# same database will realize this group deletion and delete the same group that was deleted on the hub.
UpdateTime: 60

# This is the chat format available to you! Here you can customize the output of in-game
# chat to make it suit your style. (Colour Codes are supported)

# Available Placeholders:
#  | ${WORLD} - Grab the world the player is in
#  | ${PLAYER} - Grab the player's name
#  | ${DISPLAYNAME} - Grab the player's display name
#  | ${PREFIX} - Grab the player's prefix
#  | ${SUFFIX} - Grab the player's suffix
#  | ${MESSAGE} - Grab the player's message

ChatFormat: '[${WORLD}] ${PREFIX} ${PLAYER} ${SUFFIX}: ${MESSAGE}'